name: anythingllm-dentist

networks:
  anything-llm-dentist:
    driver: bridge

services:
  anything-llm:
    container_name: anythingllm_dentist
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
      args:
        ARG_UID: ${UID:-1000}
        ARG_GID: ${GID:-1000}
    cap_add:
      - SYS_ADMIN
    volumes:
      - "./.env:/app/server/.env"
      - "./storage:/app/server/storage"
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - anything-llm-dentist
    extra_hosts:
      - "host.docker.internal:host-gateway"

